[package]
name = "coordinator-bin"  # Changed from "coordinator" to "coordinator-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coordinator-lib = { path = "../../crates/coordinator" }
