[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
prost-build = "0.13.5"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
tonic = "0.13.1"
tonic-build = "0.13.1"
